version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: python main.py

  mypy:
    image: python:alpine
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["mypy", "main.py"]

  flake8:
    image: python:alpine
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["flake8", "."]