version: "3.8"

services:
  base: &shortener_app
    build:
      context: .
      dockerfile: Dockerfile
    image: 'shortener_app'
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5000:5000"

  mypy:
    <<: *shortener_app
    volumes:
      - .:/app
    working_dir: /app
    command: ["mypy", "main.py"]

  flake8:
    <<: *shortener_app
    volumes:
      - .:/app
    working_dir: /app
    command: ["flake8", "."]