version: "3.8"

services:
  base: &shortener_app
    build:
      context: .
      dockerfile: Dockerfile
    image: 'shortener_app'
    volumes:
      - .:/app
    working_dir: /app

  server:
    <<: *shortener_app
    ports:
      - "8000:8000"
    command: ["fastapi", "dev", "--host", "0.0.0.0", "website.py"]

  mypy:
    <<: *shortener_app
    command: ["mypy", "main.py"]

  flake8:
    <<: *shortener_app
    command: ["flake8", "."]